name: addon
version: 1.0.0+1
publish_to: none
description: Add On ERP Project owned by PT Sutrakabel Intimandiri and Vocational School IPB University.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  image: ^4.0.17
  curved_navigation_bar: ^1.0.3
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  pdf: ^3.10.4
  intl: ^0.17.0
  semicircle_indicator: ^1.1.1
  shared_preferences: ^2.0.0
  connectivity_plus: ^4.0.2
  webview_flutter: ^2.0.12
  timeline_tile: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/
  - assets/bgscreen.png
