name: addon
version: 1.0.0+1
publish_to: none
description: Add On ERP Project owned by PT Sutrakabel Intimandiri and Vocational School IPB University.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  image: ^4.0.17
  salomon_bottom_bar: ^3.3.2
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  pdf: ^3.10.4
  intl: ^0.17.0
  semicircle_indicator: ^1.1.1
  shared_preferences: ^2.0.0
  connectivity_plus: ^4.0.2
  webview_flutter: ^2.0.12
  timeline_tile: ^2.0.0
  path_provider: ^2.0.2
  open_file: ^3.3.2
  path: ^1.8.0
  syncfusion_flutter_xlsio: ^21.2.3
  foundation_flutter: ^0.1.2
  provider: ^6.0.5
  badges: ^2.0.3
  universal_html: ^2.0.0
  flutter_downloader: ^1.11.3
  permission_handler: ^11.0.1
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  csv: ^5.0.2
  excel: ^2.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/
  - assets/bgscreen.png
  - assets/logo.png
